import { useEffect, useRef, useState } from 'react';
import type { DerivedModel } from '../data/schema';
import { chartColors, escapeHtml, init } from '../lib/echarts';

export default function ChartView({models}:{models:DerivedModel[]}) {
  const ref=useRef<HTMLDivElement>(null); const [kind,setKind]=useState<'price'|'weight'|'npu'>('price'); const [dark,setDark]=useState(false);
  useEffect(()=>{ const update=()=>setDark(document.documentElement.classList.contains('dark')); update(); const observer=new MutationObserver(update); observer.observe(document.documentElement,{attributes:true,attributeFilter:['class']}); return()=>observer.disconnect(); },[]);
  useEffect(()=>{ if(!ref.current)return; const colors=chartColors(dark); const chart=init(ref.current); const cfg={price:{x:'価格（円）',y:'Geekbench 6 Multi',data:models.filter(m=>m.performanceScore!==null).map(m=>[m.pricing.priceJpy,m.performanceScore!,m.modelName])},weight:{x:'重量（g）',y:'バッテリー容量（Wh）',data:models.map(m=>[m.physical.weightG,m.battery.capacityWh,m.modelName])},npu:{x:'NPU TOPS',y:'価格（円）',data:models.filter(m=>m.cpu.npuTops!==null && m.cpu.npuTops!==undefined).map(m=>[m.cpu.npuTops!,m.pricing.priceJpy,m.modelName])}}[kind]; chart.setOption({textStyle:{color:colors.text},tooltip:{formatter:(p:any)=>`${escapeHtml(p.data[2])}<br>${escapeHtml(cfg.x)}: ${escapeHtml(p.data[0])}<br>${escapeHtml(cfg.y)}: ${escapeHtml(p.data[1])}`},xAxis:{name:cfg.x,nameTextStyle:{color:colors.text},axisLabel:{color:colors.text},axisLine:{lineStyle:{color:colors.line}}},yAxis:{name:cfg.y,nameTextStyle:{color:colors.text},axisLabel:{color:colors.text},axisLine:{lineStyle:{color:colors.line}}},series:[{type:'scatter',symbolSize:14,data:cfg.data,itemStyle:{color:colors.accent}}]}); const observer=new ResizeObserver(()=>chart.resize()); observer.observe(ref.current); return()=>{observer.disconnect();chart.dispose()}; },[kind,models,dark]);
  return <><h1 className="text-3xl font-bold">比較チャート</h1><p className="mt-2 text-slate-600 dark:text-slate-300">掲載中データを散布図で比較します。</p><div className="my-5 flex gap-2">{([['price','価格 × 性能'],['weight','重量 × 電池'],['npu','NPU × 価格']] as const).map(([v,l])=><button key={v} className={`control ${kind===v?'bg-brand text-white':''}`} onClick={()=>setKind(v)}>{l}</button>)}</div><div ref={ref} className="surface h-[460px] p-3" /></>;
}
