import { useEffect, useMemo, useRef, useState } from 'react';
import type { DerivedModel } from '../data/schema';

const rows: { label:string; get:(m:DerivedModel)=>number|string|null; direction?:'higher'|'lower' }[] = [
  {label:'重量',get:m=>m.physical.weightG,direction:'lower'}, {label:'価格',get:m=>m.pricing.priceJpy,direction:'lower'}, {label:'携帯性スコア',get:m=>m.portabilityScore,direction:'higher'}, {label:'バッテリー容量',get:m=>m.battery.capacityWh,direction:'higher'}, {label:'Geekbench 6 Multi',get:m=>m.cpu.benchmarks.geekbench6Multi ?? null,direction:'higher'}, {label:'NPU',get:m=>m.cpu.npuTops ?? null,direction:'higher'}, {label:'通信',get:m=>m.connectivity.wwan?.type ?? '—'}, {label:'USB PD',get:m=>m.ports.usbPd?'対応':'—'}
];
const best = (row:typeof rows[number], models:DerivedModel[]) => { const nums=models.map(row.get).filter((x):x is number=>typeof x==='number'); if(!nums.length||!row.direction)return null; return row.direction==='higher'?Math.max(...nums):Math.min(...nums); };

export default function CompareView({ models }: {models:DerivedModel[]}) {
  const [active,setActive]=useState(1); const chart=useRef<HTMLDivElement>(null);
  const selected = useMemo(() => { if (typeof window === 'undefined') return models; const ids=new URLSearchParams(window.location.search).get('ids')?.split(',') ?? []; return ids.length ? models.filter(m=>ids.includes(m.id)) : models; }, [models]);
  useEffect(()=>{ let instance:any; (async()=>{ if(!chart.current)return; const e=await import('echarts'); instance=e.init(chart.current); instance.setOption({radar:{indicator:[{name:'性能',max:16000},{name:'携帯性',max:100},{name:'バッテリー',max:80},{name:'通信',max:1},{name:'価格',max:500000}]},legend:{},series:[{type:'radar',data:selected.map(m=>({name:m.modelName,value:[m.cpu.benchmarks.geekbench6Multi??0,m.portabilityScore,m.battery.capacityWh,m.connectivity.wwan?.type==='none'?0:1,500000-m.pricing.priceJpy]}))}]}); })(); return()=>instance?.dispose(); },[selected]);
  if (!selected.length) return <p className="surface p-6">比較する機種がありません。<a className="text-brand underline" href={import.meta.env.BASE_URL}>一覧から追加してください。</a></p>;
  return <><h1 className="mb-2 text-3xl font-bold">機種比較</h1><p className="mb-5 text-sm text-slate-600 dark:text-slate-300">最良値は強調表示します。測定法が異なる駆動時間は同列比較しません。</p><div ref={chart} className="surface mb-5 hidden h-80 p-3 md:block" aria-label="主要指標のレーダーチャート" />
  <div className="surface hidden overflow-x-auto md:block"><table className="min-w-full text-sm"><thead><tr className="border-b"><th className="sticky left-0 bg-white p-3 text-left dark:bg-slate-900">項目</th>{selected.map(m=><th className="min-w-44 p-3 text-left" key={m.id}>{m.modelName}</th>)}</tr></thead><tbody>{rows.map(row=>{const b=best(row,selected);return <tr className="border-b border-slate-100 dark:border-slate-800" key={row.label}><th className="sticky left-0 bg-white p-3 text-left font-medium dark:bg-slate-900">{row.label}</th>{selected.map(m=>{const v=row.get(m);return <td className={`p-3 ${v===b?'font-bold text-emerald-600 dark:text-emerald-400':''}`} key={m.id}>{typeof v==='number' ? row.label==='価格'?`¥${v.toLocaleString()}`:row.label==='重量'?`${v}g`:row.label==='NPU'?`${v} TOPS`:v : v??'—'}</td>})}</tr>})}</tbody></table></div>
  <section className="md:hidden"><label className="label">対向機種（スワイプ相当の切替）</label><select className="control mb-3 w-full" value={active} onChange={e=>setActive(Number(e.target.value))}>{selected.slice(1).map((m,i)=><option value={i+1} key={m.id}>{m.modelName}</option>)}</select><div className="grid gap-3">{rows.map(row=>{const base=row.get(selected[0]);const against=row.get(selected[active] ?? selected[0]);return <details className="surface p-4" key={row.label}><summary className="font-semibold">{row.label}</summary><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><p className="text-slate-500">基準: {selected[0].modelName}</p><strong>{String(base??'—')}</strong></div><div><p className="text-slate-500">対向: {(selected[active]??selected[0]).modelName}</p><strong>{String(against??'—')}</strong></div></div></details>})}</div></section></>;
}
