import { useEffect, useMemo, useRef, useState } from 'react';
import { createColumnHelper, flexRender, getCoreRowModel, getSortedRowModel, useReactTable, type SortingState } from '@tanstack/react-table';
import type { DerivedModel } from '../data/schema';
import ThemeButton from './ThemeButton';

type Props = { models: DerivedModel[] };
const fmt = new Intl.NumberFormat('ja-JP');
const href = (id: string) => `${import.meta.env.BASE_URL}models/${id}`;
const finiteLimit = (value: string | null) => { const result = Number(value); return Number.isFinite(result) && result > 0 ? result : null; };
const parseSort = (value: string | null): SortingState => (value ?? '').split(',').flatMap(part => { const [id, direction] = part.split(':'); return id && (direction === 'asc' || direction === 'desc') ? [{ id, desc: direction === 'desc' }] : []; });

export default function ModelExplorer({ models }: Props) {
  const [query, setQuery] = useState(''); const [urlQuery, setUrlQuery] = useState(''); const [makers, setMakers] = useState<string[]>([]); const [maxWeight, setMaxWeight] = useState<number | null>(null); const [maxPrice, setMaxPrice] = useState<number | null>(null); const [wwan, setWwan] = useState(false); const [compare, setCompare] = useState<string[]>([]); const [unit, setUnit] = useState<'g'|'kg'>('g'); const [sorting, setSorting] = useState<SortingState>([]);
  const initialized = useRef(false);
  const maxDataWeight = useMemo(() => Math.max(3000, ...models.map(m => m.physical.weightG)), [models]);
  const maxDataPrice = useMemo(() => Math.max(2_000_000, ...models.map(m => m.pricing.priceJpy)), [models]);
  const allMakers = useMemo(() => [...new Set(models.map(m => m.maker))].sort(), [models]);
  useEffect(() => { const timer = window.setTimeout(() => setUrlQuery(query), 250); return () => clearTimeout(timer); }, [query]);
  useEffect(() => { const p = new URLSearchParams(window.location.search); setQuery(p.get('q') ?? ''); setUrlQuery(p.get('q') ?? ''); setMakers(p.get('maker')?.split(',').filter(Boolean) ?? []); setMaxWeight(finiteLimit(p.get('weight'))); setMaxPrice(finiteLimit(p.get('price'))); setWwan(p.get('wwan') === '1'); setCompare(p.get('compare')?.split(',').filter(Boolean).slice(0, 5) ?? []); setSorting(parseSort(p.get('sort'))); initialized.current = true; }, []);
  useEffect(() => { if (!initialized.current) return; const p = new URLSearchParams(); if(urlQuery) p.set('q',urlQuery); if(makers.length) p.set('maker',makers.join(',')); if(maxWeight !== null) p.set('weight',String(maxWeight)); if(maxPrice !== null) p.set('price',String(maxPrice)); if(wwan) p.set('wwan','1'); if(compare.length) p.set('compare',compare.join(',')); if(sorting.length) p.set('sort', sorting.map(s => `${s.id}:${s.desc?'desc':'asc'}`).join(',')); history.replaceState(null, '', `${location.pathname}${p.size ? `?${p}` : ''}`); }, [urlQuery, makers, maxWeight, maxPrice, wwan, compare, sorting]);
  const filtered = useMemo(() => models.filter(m => (!query || `${m.maker} ${m.modelName} ${m.modelNumber ?? ''}`.toLowerCase().includes(query.toLowerCase())) && (!makers.length || makers.includes(m.maker)) && (maxWeight === null || m.physical.weightG <= maxWeight) && (maxPrice === null || m.pricing.priceJpy <= maxPrice) && (!wwan || m.connectivity.wwan.type !== 'none')), [models, query, makers, maxWeight, maxPrice, wwan]);
  const columns = useMemo(() => { const c = createColumnHelper<DerivedModel>(); return [c.accessor('modelName',{header:'機種',cell:i=><a className="font-semibold text-brand underline" href={href(i.row.original.id)}>{i.getValue()}</a>}), c.accessor('maker',{header:'メーカー'}), c.accessor('physical.weightG',{header:'重量',cell:i=>unit==='g'?`${i.getValue()}g`:`${(i.getValue()/1000).toFixed(2)}kg`}), c.accessor('pricing.priceJpy',{header:'価格',cell:i=>`¥${fmt.format(i.getValue())}`}), c.accessor('performanceScore',{header:'GB6 Multi',cell:i=>i.getValue() ?? '—'}), c.accessor('battery.capacityWh',{header:'電池',cell:i=>`${i.getValue()}Wh`}), c.accessor('portabilityScore',{header:'携帯性',cell:i=>`${i.getValue()}点`}), c.display({id:'compare',header:'比較',cell:i=><input aria-label={`${i.row.original.modelName}を比較`} type="checkbox" checked={compare.includes(i.row.original.id)} onChange={() => setCompare(prev => prev.includes(i.row.original.id) ? prev.filter(x=>x!==i.row.original.id) : prev.length < 5 ? [...prev,i.row.original.id] : prev)} />})]; },[compare,unit]);
  const table = useReactTable({data:filtered, columns, state:{sorting}, onSortingChange:setSorting, getCoreRowModel:getCoreRowModel(), getSortedRowModel:getSortedRowModel()});
  const clear = () => { setQuery(''); setUrlQuery(''); setMakers([]); setMaxWeight(null); setMaxPrice(null); setWwan(false); setSorting([]); };
  return <><section className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-brand">外出先で選ぶ、スペックの根拠。</p><h1 className="mt-1 text-3xl font-bold">モバイルPC比較</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{filtered.length} 件 / {models.length} 件を表示。条件はURLで共有できます。</p></div><div className="flex gap-2"><button className="control" onClick={()=>setUnit(unit==='g'?'kg':'g')}>{unit === 'g' ? 'kg 表示' : 'g 表示'}</button><ThemeButton /></div></section>
  <div className="grid gap-5 lg:grid-cols-[260px_1fr]"><aside className="surface h-fit p-4"><div className="mb-3 flex justify-between"><h2 className="font-bold">絞り込み</h2><button className="text-sm text-brand underline" onClick={clear}>リセット</button></div><label className="label" htmlFor="model-search">検索</label><input id="model-search" className="control mb-4 w-full" value={query} onChange={e=>setQuery(e.target.value)} placeholder="型番・機種名" /><span className="label">メーカー</span><div className="mb-4 space-y-1">{allMakers.map(m=><label className="flex gap-2 text-sm" key={m}><input type="checkbox" checked={makers.includes(m)} onChange={()=>setMakers(x=>x.includes(m)?x.filter(a=>a!==m):[...x,m])}/>{m}</label>)}</div><label className="mb-2 flex gap-2 text-sm"><input type="checkbox" checked={maxWeight !== null} onChange={e=>setMaxWeight(e.target.checked ? maxDataWeight : null)}/>重量を上限指定</label><label className="label" htmlFor="weight-limit">重量 ≤ {maxWeight ?? '上限なし'}{maxWeight !== null && 'g'}</label><input id="weight-limit" className="mb-4 w-full" disabled={maxWeight === null} type="range" min="300" max={maxDataWeight} step="50" value={maxWeight ?? maxDataWeight} onChange={e=>setMaxWeight(Number(e.target.value))}/><label className="mb-2 flex gap-2 text-sm"><input type="checkbox" checked={maxPrice !== null} onChange={e=>setMaxPrice(e.target.checked ? maxDataPrice : null)}/>価格を上限指定</label><label className="label" htmlFor="price-limit">価格 ≤ {maxPrice === null ? '上限なし' : `¥${fmt.format(maxPrice)}`}</label><input id="price-limit" className="mb-4 w-full" disabled={maxPrice === null} type="range" min="100000" max={maxDataPrice} step="10000" value={maxPrice ?? maxDataPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={wwan} onChange={e=>setWwan(e.target.checked)}/>LTE / 5G 対応</label></aside>
  <section className="surface overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-800">{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=>{const sorted=h.column.getIsSorted(); return <th aria-sort={sorted === 'asc' ? 'ascending' : sorted === 'desc' ? 'descending' : 'none'} className="whitespace-nowrap p-3" key={h.id}>{h.isPlaceholder ? null : <button onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())}{sorted==='asc'?' ↑':sorted==='desc'?' ↓':''}</button>}</th>})}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr className="border-t border-slate-100 dark:border-slate-800" key={r.id}>{r.getVisibleCells().map(c=><td className="p-3" key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{filtered.map(m=><article className="rounded-xl border border-slate-200 p-4 dark:border-slate-700" key={m.id}><div className="flex justify-between gap-3"><div><a className="font-bold text-brand underline" href={href(m.id)}>{m.modelName}</a><p className="text-sm">{m.maker} · {unit==='g'?`${m.physical.weightG}g`:`${(m.physical.weightG/1000).toFixed(2)}kg`}</p></div><input aria-label="比較に追加" type="checkbox" checked={compare.includes(m.id)} onChange={()=>setCompare(x=>x.includes(m.id)?x.filter(a=>a!==m.id):x.length<5?[...x,m.id]:x)}/></div><div className="mt-3 flex gap-2"><span className="chip">¥{fmt.format(m.pricing.priceJpy)}</span><span className="chip">携帯性 {m.portabilityScore}</span><span className="chip">{m.connectivity.wwan.type === 'none' ? 'Wi-Fi' : m.connectivity.wwan.type}</span></div></article>)}</div></section></div>
  {compare.length > 0 && <div className="fixed inset-x-0 bottom-0 z-10 border-t border-cyan-200 bg-white/95 p-3 shadow-lg backdrop-blur dark:bg-slate-900/95"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><span className="text-sm font-medium">比較対象 {compare.length}/5</span><div className="flex gap-2"><button className="control" onClick={()=>setCompare([])}>解除</button><a className="rounded-lg bg-brand px-3 py-2 text-sm font-semibold text-white" href={`${import.meta.env.BASE_URL}compare?ids=${compare.join(',')}`}>比較する</a></div></div></div>}
  </>;
}
